### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Alxeph** [TheRetroSpecter/VsRetro-Psych-Public#4]
### Describe your bug here.

The game crashes before the end of the 2nd song in the 1st week
![image](https://github.com/TheRetroSpecter/VsRetro-Psych-Public/assets/135551490/0d5f1412-8e25-40ae-b593-813c40ebf1e9)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by NeeEoo** [comment]
Disable Motion in settings

**Comment by Alxeph** [comment]
> Disable Motion in settings

thanks it worked

**Comment by NeeEoo** [comment]
But can i get your current settings?

**Comment by Alxeph** [comment]
yeah sorry do you want me to get screenshots of all the settings or?

**Comment by NeeEoo** [comment]
That should suffice. You could also just write the stuff like

Motion unchecked
Particles unchecked
background level 0

**Comment by Alxeph** [comment]
alright they are

Motion unchecked
Particles checked
background level 0
optimize unchecked
trails checked
window shake checked
screen shake checked
camera zooms checked flashing lights checked
time bar disabled
note spalshes checked
hide hud unchecked
score text zoom on hit checked
opponent noteskins checked
player noteskins checked
health bar transparency 100%
fps counter checked
