### ISSUE TITLE
I want to add a character to Retro's mod because of a cover I made.

### ISSUE THREAD

**Issue by bluethewolf02** [TheRetroSpecter/VsRetro-Psych-Public#5]
### Describe your bug here.

Whenever I add a character, it says "Invalid char 34 at position 2577". Could you explain what happened please?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by NeeEoo** [comment]
Send the json file...

**Comment by ShiftyBlue02** [comment]
![Void_assets](https://github.com/TheRetroSpecter/VsRetro-Psych-Public/assets/152831839/eb2cc966-d92f-4d17-938b-8a44c3aadcc1)
[voidmad.json](https://github.com/TheRetroSpecter/VsRetro-Psych-Public/files/13701620/voidmad.json)

**Comment by ShiftyBlue02** [comment]
sorry im late, hehe, anw i cant send the xml file

**Comment by NexIsDumb** [comment]
ohm
this is not retro's mod fault lmfao

**Comment by ShiftyBlue02** [comment]
ik just curious why i cant add the character in

**Comment by ShiftyBlue02** [comment]
Why? I alr know how to add characters to Retro's mod now. Sorry for the inconvenience. :)
